name: platform_version
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.platform_version
        pluginClass: PlatformVersionPlugin
      ios:
        pluginClass: PlatformVersionPlugin
      linux:
        pluginClass: PlatformVersionPlugin
      macos:
        pluginClass: PlatformVersionPlugin
      windows:
        pluginClass: PlatformVersionPluginCApi
      web:
        pluginClass: PlatformVersionWeb
        fileName: platform_version_web.dart



