name: platform_version
description: "A cross-platform Flutter plugin to retrieve the OS/platform version and device/system information. Supports Android, iOS, Web, Windows, macOS and Linux."
version: 0.0.2
homepage: "https://github.com/SwanFlutter/platform_version"

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.platform_version
        pluginClass: PlatformVersionPlugin
      ios:
        pluginClass: PlatformVersionPlugin
      linux:
        pluginClass: PlatformVersionPlugin
      macos:
        pluginClass: PlatformVersionPlugin
      windows:
        pluginClass: PlatformVersionPluginCApi
      web:
        pluginClass: PlatformVersionWeb
        fileName: platform_version_web.dart



